# -*- coding: utf-8 -*-
"""MachineProblem1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mmAGl2icoHAoNirJPjawZZhMlPubogtR

**Hour 1 – Setup & Dataset Exploration**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load iris dataset
iris_df = pd.read_csv("iris_dataset.csv")

# Display first few rows
print(iris_df.head(5))

# Summary info
print("\nDataset Info:")
print(iris_df.info())

# Statistical summary
print("\nDescriptive Statistics:")
print(iris_df.describe())

# Class distribution
print("\nSpecies Distribution:")
print(iris_df['species'].value_counts())

# Histogram of sepal length
iris_df['sepal length (cm)'].hist()
plt.title("Sepal Length Distribution")
plt.show()

# Scatter plot with hue by species
sns.scatterplot(data=iris_df, x="petal length (cm)", y="petal width (cm)", hue="species")
plt.title("Petal Length vs Width by Species")
plt.show()

"""Mini-task: Students answer:

• What is the input (features)?
  sepal length (cm), sepal width (cm), petal length (cm), petal width (cm)

• What is the output (label)?
  species (setosa, versicolor, virginica)

• Is this supervised or unsupervised learning?
  This is supervised learning because we have labeled data (known species)

**Hour 2 – Train-Test Split & Baseline Model**
"""

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

#Features and target
X = iris_df.drop("species", axis=1)
Y = iris_df["species"]

#Train-test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

#Train Decision Tree
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, Y_train)

#Predictions
Y_pred = clf.predict(X_test)

"""**Hour 3 - Evaluation & Reflection**"""

#Accuracy
print("Accuracy:", accuracy_score(Y_test, Y_pred))

#Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, Y_pred))